# Generated by Django 5.0.6 on 2024-06-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Сообщение", "verbose_name_plural": "Сообщения"},
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="mail_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало отправки рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время первой отправки рассылки",
            ),
        ),
    ]
