# Generated by Django 4.2.2 on 2024-06-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "newsletters",
            "0003_alter_message_options_alter_newsletter_mail_datetime_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_manage_newsletter_status", "Can manage newsletter status")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
