# Generated by Django 4.2.2 on 2024-06-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(
                help_text="Введите содержимое статьи", verbose_name="Содержимое"
            ),
        ),
    ]
